global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:8000']

  - job_name: 'documents'
    static_configs:
      - targets: ['documents:8001']

  - job_name: 'websearch'
    static_configs:
      - targets: ['websearch:8002']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
